sudo: required
language: generic

services:
  - docker

before_install:
  - docker build -t itaybracha11/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true itaybracha11/docker-react npm run test